suitenumerique/messages

src/backend/core/api/openapi.json, src/backend/core/api/serializers.py, src/backend/core/forms.py, src/backend/core/services/import_service.py, src/backend/core/tests/api/test_messages_import.py, src/backend/core/tests/services/test_import_service.py
Enhance support for MBOX files from various email export tools by handling
both extensionless files and text/plain MIME type. This improves compatibility
with different export formats while maintaining security through proper
validation.
Changes:
- Add support for files named "mbox" without extension
- Allow text/plain MIME type for MBOX files (common in webmail exports)
- Keep application/mbox as the primary MIME type for MBOX files
- Update validation to check both MIME types and file extensions
- Add test cases for extensionless files and text/plain MIME type
- Update error messages to be more descriptive about supported formats
The validation now handles:
- Files with .mbox extension (application/mbox or text/plain MIME type)
- Files named "mbox" without extension
- Maintains strict …
=> ✨(backend) support files named "mbox" without extension

src/backend/core/api/openapi.json, src/backend/core/api/serializers.py, src/backend/core/api/viewsets/label.py, src/backend/core/tests/api/test_labels.py, src/backend/core/urls.py
Allow to create, update and delete Label and add or delete label to a thread.
Display list of labels as tree structure.
TODO:
=> endpoints to manage labels and retrieve label list in a tree structure

src/backend/core/api/viewsets/import_message.py, src/backend/core/mda/inbound.py, src/backend/core/tests/api/test_messages_import.py
Avoid duplicate threads when importing the same file multiple times.
Changes:
- Moved duplicate message check to the start of deliver_inbound_message
- Added special thread finding logic for imports that:
- First checks for existing threads by message IDs (in_reply_to and references)
- Falls back to subject-based matching if no message IDs are found
- Uses canonical subject matching to handle reply/forward prefixes
- Maintains proper threading relationships while preventing duplicate threads
- Preserves existing behavior for normal message delivery
This ensures that:
- Messages are properly threaded during import
- No duplicate threads are created when importing the same file multiple times
- Threading is maintained even when messages are processed in different orders
- Existing threads …
=> 🐛(backend) prevent duplicate threads during message import

src/backend/core/api/viewsets/task.py, src/backend/core/tasks.py, src/backend/core/tests/import_messages/test_file_import.py, src/backend/core/tests/import_messages/test_imap_import.py, src/backend/core/tests/services/test_import_service.py, src/backend/core/tests/test_tasks.py
Ensure consistent state reporting across import task updates
=> 🐛(backend) fix task response returned

src/frontend/src/features/i18n/translations.json, src/frontend/src/features/layouts/components/thread-panel/index.tsx
When a mailbox has no threads, a button should be displayed to open the modal to import messages from an old mailbox.
=> ✨(front) display a button to import a message when no thread

src/backend/core/api/serializers.py, src/backend/core/api/viewsets/label.py, src/backend/core/models.py, src/backend/core/tests/api/test_labels.py
Put the logic into Label model's save() method to guarantee the invariant always holds, even when using the admin interfacee uses, the shell, bulk operations, or any code path.
=> ♻️(labels) move parent labels creation logic

src/backend/messages/settings.py
- Added SECURE_REDIRECT_EXEMPT pattern for api/v1.0/mta/ endpoints
- Prevents Django from forcing HTTPS redirects on internal cluster communication
- Fixes internal deployment issues where MTA endpoints need HTTP access
=> 🔧(backend) prevent SSL redirect for internal MTA URLs

src/backend/core/mda/inbound.py, src/backend/core/mda/rfc5322/parser.py, src/backend/core/tests/api/test_messages_import_labels_en.py, src/backend/core/tests/api/test_messages_import_labels_fr.py, src/backend/core/tests/resources/All mail Including Spam and Trash.mbox, src/backend/core/tests/resources/Tous les messages, y compris ceux du dossier Spam .mbox
Add comprehensive Gmail label import functionality for mbox files with support for both English and French Gmail labels.
Features:
- Map Gmail system labels to internal message flags (is_draft, is_sender, is_starred, etc.)
- Handle read/unread status from Gmail labels (Ouvert/Opened, Non lus/Unread)
- Create user labels for non-system Gmail labels
- Support hierarchical labels with proper parent/child relationships
- Ignore Gmail system labels that shouldn't be created as user labels
- Special handling for sent/draft messages (automatically marked as read)
Test coverage:
- Label creation and flag mapping for both languages
- UTF-8 encoded label handling
- Hierarchical label structure validation
- Read/unread status verification
- Authentication and authorization requirements
- Thread …
=> ✨(backend) import label gmail from mbox

src/frontend/src/features/controlled-modals/message-importer/index.tsx, src/frontend/src/features/providers/mailbox.tsx
When a message imported succeeded, the labels list should be refreshed.
=> 🐛(front) invalidate labels query after import

src/backend/core/api/viewsets/label.py, src/backend/core/models.py
- Change label sorting from name-based to slug-based ordering in list view
- Use slug ordering for initial queryset to ensure consistent sorting
- Maintain name-based sorting in create method for consistency
- Fixes issue where "État civil et cimetière" appeared at the end
The slug-based sorting provides more predictable alphabetical ordering since slugs are normalized versions of names without accents.
=> 🐛(api) correct alphabetical sorting of labels with accented characters

src/frontend/src/features/i18n/conf.ts, src/frontend/src/features/layouts/components/main/language-picker.tsx, src/frontend/src/pages/_app.tsx
Currently UI Kit components are not internationalized, we pass the active language to CunninghamProvider to fix that.
=> 🌐(frontend) pass current language to CunninghamProvider

src/backend/core/api/viewsets/contacts.py, src/backend/core/mda/outbound.py, src/backend/core/mda/rfc5322/__init__.py, src/backend/core/mda/rfc5322/composer.py, src/backend/core/tests/api/test_contacts.py, src/backend/core/tests/mda/test_rfc5322_composer.py, src/backend/core/urls.py
- Add ability to search contacts by multiple keywords (AND logic) on name and email, in contacts endpoint.
- Adapt and enrich tests to cover multi-word search, case sensitivity, and name/email combination.
=> ✨(api) add multi-word search on contact name and email

src/frontend/src/features/blocknote/quoted-message-block/index.tsx, src/frontend/src/features/forms/components/message-editor/index.tsx, src/frontend/src/features/forms/components/message-form/attachment-uploader.tsx, src/frontend/src/features/forms/components/search-filters-form/index.tsx, src/frontend/src/features/layouts/components/thread-panel/components/thread-item/index.tsx, src/frontend/src/features/layouts/components/thread-view/components/thread-attachment-list/attachment-item.tsx, src/frontend/src/features/layouts/components/thread-view/components/thread-attachment-list/index.tsx, src/frontend/src/features/layouts/components/thread-view/components/thread-message/index.tsx, src/frontend/src/features/utils/attachment-helper/index.ts, src/frontend/src/features/utils/date-helper.ts, src/frontend/src/features/utils/search-helper/index.ts
For Blocknote and Intl methods, we must provide a locale without region. So we use `i18n.resolvedLanguage` instead of `i18n.language` to fix that.
=> 🐛(frontend) use i18n.resolvedLanguage to get locale

src/backend/core/api/serializers.py, src/backend/core/models.py, src/backend/core/tests/api/test_users.py, src/backend/core/tests/models/test_user_abilities.py
- Add get_abilities() method to User model to determine user permissions
- Add abilities field to UserSerializer to expose permissions via API
- Implement permission logic for create_maildomains and view_maildomains
- Add comprehensive tests for User model abilities method
- Add integration tests for abilities field in users/me endpoint
- Support superuser+staff, mail domain access, and regular user scenarios
The abilities system provides granular permission control for mail domain operations, allowing the frontend to adapt UI based on user capabilities.
=> ✨(backend) add user abilities system for mail domain permissions

src/backend/core/api/serializers.py, src/backend/core/api/viewsets/maildomain.py, src/backend/core/models.py, src/backend/core/tests/api/test_admin_maildomains_list.py, src/backend/core/tests/models/test_maildomain.py
- Add get_abilities() method to MailDomain model for permission-based abilities
- Update MailDomainAdminSerializer to inherit from AbilitiesModelSerializer
- Add RetrieveModelMixin to MailDomainAdminViewSet for detail endpoints
- Optimize queries with JOIN and annotation for regular users
- Add prefetch_related for superusers to avoid N+1 queries
- Add comprehensive tests for abilities functionality and query optimization
- Add new test file for MailDomain model abilities
The abilities field dynamically controls user permissions based on their role in the mail domain, with optimized database queries to maintain performance.
=> ✨(api) add dynamic abilities field to MailDomain API

src/frontend/src/features/layouts/components/main/index.tsx, src/frontend/src/features/layouts/components/main/no-mailbox.tsx
There were some issues when the user has no mailbox. The left panel was displayed on desktop but there is nothing within. Furthermore, a translation key was wrong.
=> 💄(front) fix layout when there is no mailbox

src/frontend/src/features/forms/components/combobox/index.tsx
Fix an issue that cause the input cursor to jump when user types in the combobox input
=> 🐛(front) prevent input cursor to jump on update value

src/frontend/src/features/layouts/components/mailbox-panel/components/mailbox-actions/index.tsx
In the mailbox actions, add a mailbox settings dropdown menu with an option to import messages.
=> ✨(front) add mailbox settings dropdown menu

src/frontend/src/features/config/constants.ts, src/frontend/src/features/layouts/components/admin/modal-create-address/index.tsx, src/frontend/src/features/providers/admin-maildomain.tsx, src/frontend/src/pages/domain/[maildomainId]/index.tsx
When an admin creates a new mailbox and there was on the first page of the mailboxes, the data was not refreshed.
=> 🐛(frontend) invalidate properly mailbox query on mailbox creation

src/frontend/src/features/layouts/components/thread-view/index.tsx
The intersection threshold to mark a message as read was 0.95. That means that 95% of the message must be displayed on the screen to trigger the observer so with long messages or on small viewport, in some cases the message could be not mark as read.
=> 🐛(front) decrease intersection threshold to mark messages as read
